# A default Taskfile.yml for Create Go App project.
# Author: Vic Shóstak <truewebartisans@gmail.com> (https://1wa.co)

version: "2"

tasks:
  # Default task
  default:
    cmds:
      - task: backend-run

  # Backend tasks
  backend-test:
    dir: ./backend
    cmds:
      - task test
  backend-run:
    dir: ./backend
    cmds:
      - task run
  backend-build:
    dir: ./backend
    cmds:
      - task build

  # Docker tasks
  docker-build:
    dir: ./backend
    cmds:
      - docker build -t dokerb .
  docker-run:
    cmds:
      - docker run --rm -p 5000:5000 dokerb
