basePath: /api
definitions:
  apiserver.CalcEstimate:
    properties:
      estimate:
        $ref: '#/definitions/apiserver.Estimate'
        format: Estimate
      hint:
        example: not all users provided estimates
        format: string
        type: string
      message:
        example: warning
        format: string
        type: string
      users:
        example:
        - Tigger
        format: '[]string'
        items:
          type: string
        type: array
    type: object
  apiserver.DocEntry:
    properties:
      name:
        example: GitHub
        format: string
        type: string
      url:
        example: https://github.com/HaRo87
        format: string
        type: string
    type: object
  apiserver.DocResponse:
    properties:
      message:
        example: ok
        format: string
        type: string
      results:
        items:
          $ref: '#/definitions/apiserver.DocEntry'
        type: array
    type: object
  apiserver.ErrorResponse:
    properties:
      message:
        example: error
        format: string
        type: string
      reason:
        example: oops, something went wrong
        format: string
        type: string
    type: object
  apiserver.Estimate:
    properties:
      effort:
        example: 1.5
        format: float64
        type: number
      standarddeviation:
        example: 0.2
        format: float64
        type: number
    type: object
  apiserver.GeneralResponse:
    properties:
      message:
        example: ok
        format: string
        type: string
      route:
        example: /sessions/token
        format: string
        type: string
    type: object
  apiserver.PerUserEstimate:
    properties:
      b:
        example: 1.5
        format: float64
        type: number
      id:
        example: TEST01
        format: string
        type: string
      m:
        example: 2
        format: float64
        type: number
      user:
        example: Tigger
        format: string
        type: string
      w:
        example: 3.6
        format: float64
        type: number
    type: object
  apiserver.PerUserEstimateResponse:
    properties:
      estimates:
        format: '[]datastore.Estimate'
        items:
          $ref: '#/definitions/datastore.Estimate'
        type: array
      message:
        example: ok
        format: string
        type: string
    type: object
  apiserver.Task:
    properties:
      id:
        example: TEST01
        format: string
        type: string
      summary:
        example: a sample task
        format: string
        type: string
    type: object
  apiserver.TaskResponse:
    properties:
      message:
        example: ok
        format: string
        type: string
      tasks:
        format: '[]datastore.Task'
        items:
          $ref: '#/definitions/datastore.Task'
        type: array
    type: object
  apiserver.User:
    properties:
      name:
        example: Tigger
        format: string
        type: string
    type: object
  apiserver.UsersResponse:
    properties:
      message:
        example: ok
        format: string
        type: string
      users:
        example:
        - Tigger
        - Rabbit
        format: '[]string'
        items:
          type: string
        type: array
    type: object
  datastore.Estimate:
    properties:
      bestCase:
        type: number
      mostLikelyCase:
        type: number
      taskID:
        type: string
      userName:
        type: string
      worstCase:
        type: number
    type: object
  datastore.Task:
    properties:
      effort:
        type: number
      id:
        type: string
      standardDeviation:
        type: number
      summary:
        type: string
    type: object
host: localhost:5000
info:
  contact:
    name: HaRo87
    url: https://github.com/HaRo87
  description: A backend for playing Planning Poker with Delphi estimate method.
  license:
    name: MIT
    url: https://github.com/HaRo87/dokerb/blob/main/LICENSE
  title: Doker Backend API
  version: 0.1.0
paths:
  /docs:
    get:
      description: Get a list of helpful documentation resources
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiserver.DocResponse'
      summary: Get the documentation info
      tags:
      - documentation
  /sessions:
    post:
      description: Creates a new Doker session and responds with the corresponding
        token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiserver.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
      summary: Create a new Doker session
      tags:
      - session
  /sessions/{token}:
    delete:
      description: Deletes a existing Doker session based on the provided token
      parameters:
      - description: Session Token
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiserver.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
      summary: Delete a existing Doker session
      tags:
      - session
  /sessions/{token}/estimates:
    get:
      description: Gets all estimates of all existing users of all existing tasks
        inside a existing session
      parameters:
      - description: Session Token
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiserver.PerUserEstimateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
      summary: Get the estimates of all users for all tasks
      tags:
      - estimate
    post:
      description: Adds a estimate of a existing user of a existing task inside a
        existing session
      parameters:
      - description: Session Token
        in: path
        name: token
        required: true
        type: string
      - description: New Estimate
        in: body
        name: estimate
        required: true
        schema:
          $ref: '#/definitions/apiserver.PerUserEstimate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiserver.GeneralResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
      summary: Add the estimate of a user for a task
      tags:
      - estimate
  /sessions/{token}/estimates/{id}:
    get:
      description: Gets the average estimate of all existing users of a existing task
        inside a existing session
      parameters:
      - description: Session Token
        in: path
        name: token
        required: true
        type: string
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiserver.CalcEstimate'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
      summary: Get the average estimate of all users for a specific task
      tags:
      - estimate
  /sessions/{token}/estimates/{id}/users/distance:
    get:
      description: Gets the users with max distance in their estimates of a existing
        task inside a existing session
      parameters:
      - description: Session Token
        in: path
        name: token
        required: true
        type: string
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiserver.UsersResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
      summary: Get the users with max distance between their estimates for a specific
        task
      tags:
      - estimate
  /sessions/{token}/estimates/{user}/{id}:
    delete:
      description: Removes a estimate of a existing user of a existing task inside
        a existing session
      parameters:
      - description: Session Token
        in: path
        name: token
        required: true
        type: string
      - description: User Name
        in: path
        name: user
        required: true
        type: string
      - description: Task ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiserver.GeneralResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
      summary: Remove the estimate of a user for a task
      tags:
      - estimate
  /sessions/{token}/tasks:
    get:
      description: Gets all tasks of an existing session
      parameters:
      - description: Session Token
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiserver.TaskResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
      summary: Get the tasks of a session
      tags:
      - task
    post:
      description: Adds a new (non-existing) task to an existing session
      parameters:
      - description: Session Token
        in: path
        name: token
        required: true
        type: string
      - description: New Task
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/apiserver.Task'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiserver.GeneralResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
      summary: Add a new task to a existing session
      tags:
      - task
  /sessions/{token}/tasks/{id}:
    delete:
      description: Removes a existing task from an existing session
      parameters:
      - description: Session Token
        in: path
        name: token
        required: true
        type: string
      - description: ID of the task
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiserver.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
      summary: Remove a task from a session
      tags:
      - task
    put:
      description: Updates a estimate of a existing task inside a existing session
      parameters:
      - description: Session Token
        in: path
        name: token
        required: true
        type: string
      - description: ID of the task
        in: path
        name: id
        required: true
        type: string
      - description: New Estimate
        in: body
        name: estimate
        required: true
        schema:
          $ref: '#/definitions/apiserver.Estimate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiserver.GeneralResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
      summary: Update the estimate of a task
      tags:
      - task
  /sessions/{token}/tasks/{id}/estimate:
    delete:
      description: Removes the estimate from an existing task
      parameters:
      - description: Session Token
        in: path
        name: token
        required: true
        type: string
      - description: ID of the task
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiserver.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
      summary: Delete the estimate from a task
      tags:
      - task
  /sessions/{token}/users:
    get:
      description: Gets all users of an existing session
      parameters:
      - description: Session Token
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiserver.UsersResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
      summary: Get the users of an existing session
      tags:
      - user
    post:
      description: Adds a new (non-existing) user to an existing session
      parameters:
      - description: Session Token
        in: path
        name: token
        required: true
        type: string
      - description: New User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/apiserver.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiserver.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
      summary: Add a new user to a existing session
      tags:
      - user
  /sessions/{token}/users/{name}:
    delete:
      description: Removes a existing user from an existing session
      parameters:
      - description: Session Token
        in: path
        name: token
        required: true
        type: string
      - description: Name of the user
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apiserver.GeneralResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apiserver.ErrorResponse'
      summary: Remove a user from a session
      tags:
      - user
swagger: "2.0"
