# Server config
server:
  host: 0.0.0.0 # if you want to run this API server from a Docker container, set it to 0.0.0.0
  port: 5000

# Authentication config  
auth:
  type: simple-auth
  signingKey: TEST1234

# Database config
database:
  location: my.db

# Static files config
static:
  prefix: /
  path: ./static

simple-auth:
  user: Tigger
  password: JUMP1234
