on: push
name: Testing Go Code
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: run tests and build
      uses: cedrickring/golang-action@1.6.0
      env:
        GO111MODULE: "on"
        PROJECT_PATH: "./backend"